# Generated by Django 5.0.6 on 2026-01-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_tagmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamemodel",
            options={"ordering": ["-pub_time"]},
        ),
        migrations.AlterModelOptions(
            name="tagmodel",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelTable(
            name="gamemodel",
            table="game",
        ),
        migrations.AlterModelTable(
            name="tagmodel",
            table="tag",
        ),
    ]
